package Calculadora;

import java.awt.Color;

public class Calculadora extends javax.swing.JFrame {
    public Calculadora() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        jPanel1.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_num1 = new javax.swing.JLabel();
        jl_num2 = new javax.swing.JLabel();
        jl_res = new javax.swing.JLabel();
        jtf_num1 = new javax.swing.JTextField();
        jtf_num2 = new javax.swing.JTextField();
        jtf_res = new javax.swing.JTextField();
        jb_suma = new javax.swing.JButton();
        jb_resta = new javax.swing.JButton();
        lb_mod = new javax.swing.JButton();
        jb_div = new javax.swing.JButton();
        jb_mult = new javax.swing.JButton();
        jb_clean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("jframe_calculadora"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Calculadora V1.0", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jl_num1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_num1.setText("Número 1:");

        jl_num2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_num2.setText("Número 2:");

        jl_res.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_res.setText("Resultado:");

        jtf_num1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_num1ActionPerformed(evt);
            }
        });

        jtf_num2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jtf_res.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jb_suma.setText("+");
        jb_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sumaActionPerformed(evt);
            }
        });

        jb_resta.setText("-");
        jb_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_restaActionPerformed(evt);
            }
        });

        lb_mod.setText("%");
        lb_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_modActionPerformed(evt);
            }
        });

        jb_div.setText("/");
        jb_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_divActionPerformed(evt);
            }
        });

        jb_mult.setText("*");
        jb_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_multActionPerformed(evt);
            }
        });

        jb_clean.setText("Limpiar");
        jb_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jb_suma)
                            .addGap(11, 11, 11)
                            .addComponent(jb_resta)
                            .addGap(11, 11, 11)
                            .addComponent(lb_mod)
                            .addGap(11, 11, 11)
                            .addComponent(jb_div))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jb_mult)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jb_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_num1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_num2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_res, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_res, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_num1)
                    .addComponent(jtf_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_num2)
                    .addComponent(jtf_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_res)
                    .addComponent(jtf_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_suma)
                    .addComponent(jb_resta)
                    .addComponent(lb_mod)
                    .addComponent(jb_div))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_mult)
                    .addComponent(jb_clean))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cleanActionPerformed
        this.jtf_num1.setText("");
        this.jtf_num2.setText("");
        this.jtf_res.setText("");
    }//GEN-LAST:event_jb_cleanActionPerformed

    private void jb_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_multActionPerformed
        float num1; //Crear una variable para guardar el texto de jtf_num1
        float num2; //Crear una variable para guardar el texto de jtf_num2
        num1 = Float.parseFloat(this.jtf_num1.getText()); //Convierte el texto de jtf_num1 a flotante y lo guarda en num1
        num2 = Float.parseFloat(this.jtf_num2.getText()); //Convierte el texto de jtf_num2 a flotante y lo guarda en num2
        float res = num1 * num2; //Crea una variable y guarda el valor de la multiplicación de num1 y num2
        this.jtf_res.setText(String.valueOf(res)); //Muestra el valor de res en la jft_res
    }//GEN-LAST:event_jb_multActionPerformed

    private void jb_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_divActionPerformed
        float num1; //Crear una variable para guardar el texto de jtf_num1
        float num2; //Crear una variable para guardar el texto de jtf_num2
        num1 = Float.parseFloat(this.jtf_num1.getText()); //Convierte el texto de jtf_num1 a flotante y lo guarda en num1
        num2 = Float.parseFloat(this.jtf_num2.getText()); //Convierte el texto de jtf_num2 a flotante y lo guarda en num2
        float res = num1 / num2; //Crea una variable y guarda el valor de la división de num1 y num2
        this.jtf_res.setText(String.valueOf(res)); //Muestra el valor de res en la jft_res
    }//GEN-LAST:event_jb_divActionPerformed

    private void lb_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_modActionPerformed
        float num1; //Crear una variable para guardar el texto de jtf_num1
        float num2; //Crear una variable para guardar el texto de jtf_num2
        num1 = Float.parseFloat(this.jtf_num1.getText()); //Convierte el texto de jtf_num1 a flotante y lo guarda en num1
        num2 = Float.parseFloat(this.jtf_num2.getText()); //Convierte el texto de jtf_num2 a flotante y lo guarda en num2
        float res = num1 % num2; //Crea una variable y guarda el valor del modulo de num1 y num2
        this.jtf_res.setText(String.valueOf(res)); //Muestra el valor de res en la jft_res
    }//GEN-LAST:event_lb_modActionPerformed

    private void jb_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_restaActionPerformed
        float num1; //Crear una variable para guardar el texto de jtf_num1
        float num2; //Crear una variable para guardar el texto de jtf_num2
        num1 = Float.parseFloat(this.jtf_num1.getText()); //Convierte el texto de jtf_num1 a flotante y lo guarda en num1
        num2 = Float.parseFloat(this.jtf_num2.getText()); //Convierte el texto de jtf_num2 a flotante y lo guarda en num2
        float res = num1 - num2; //Crea una variable y guarda el valor de la resta de num1 y num2
        this.jtf_res.setText(String.valueOf(res)); //Muestra el valor de res en la jft_res
    }//GEN-LAST:event_jb_restaActionPerformed

    private void jb_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sumaActionPerformed
        float num1; //Crear una variable para guardar el texto de jtf_num1
        float num2; //Crear una variable para guardar el texto de jtf_num2
        num1 = Float.parseFloat(this.jtf_num1.getText()); //Convierte el texto de jtf_num1 a flotante y lo guarda en num1
        num2 = Float.parseFloat(this.jtf_num2.getText()); //Convierte el texto de jtf_num2 a flotante y lo guarda en num2
        float res = num1 + num2; //Crea una variable y guarda el valor de la suma de num1 y num2
        this.jtf_res.setText(String.valueOf(res)); //Muestra el valor de res en la jft_res
    }//GEN-LAST:event_jb_sumaActionPerformed

    private void jtf_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_num1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_clean;
    private javax.swing.JButton jb_div;
    private javax.swing.JButton jb_mult;
    private javax.swing.JButton jb_resta;
    private javax.swing.JButton jb_suma;
    private javax.swing.JLabel jl_num1;
    private javax.swing.JLabel jl_num2;
    private javax.swing.JLabel jl_res;
    private javax.swing.JTextField jtf_num1;
    private javax.swing.JTextField jtf_num2;
    private javax.swing.JTextField jtf_res;
    private javax.swing.JButton lb_mod;
    // End of variables declaration//GEN-END:variables
}
