/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class MayorMenor extends javax.swing.JFrame {

    /**
     * Creates new form MayorMenor
     */
    public MayorMenor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.ButtonGroup();
        jp_in = new javax.swing.JPanel();
        jl_n3 = new javax.swing.JLabel();
        jl_n2 = new javax.swing.JLabel();
        jl_n1 = new javax.swing.JLabel();
        jtf_n1 = new javax.swing.JTextField();
        jtf_n2 = new javax.swing.JTextField();
        jtf_n3 = new javax.swing.JTextField();
        lp_rb = new javax.swing.JPanel();
        jrb_may = new javax.swing.JRadioButton();
        jrb_men = new javax.swing.JRadioButton();
        jp_bt = new javax.swing.JPanel();
        jb_com = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jp_in.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Mayor & Menor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jl_n3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_n3.setText("Numero 3:");

        jl_n2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_n2.setText("Numero 2:");

        jl_n1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_n1.setText("Numero 1:");

        jtf_n1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jtf_n2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jtf_n3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout jp_inLayout = new javax.swing.GroupLayout(jp_in);
        jp_in.setLayout(jp_inLayout);
        jp_inLayout.setHorizontalGroup(
            jp_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_inLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jp_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_inLayout.createSequentialGroup()
                        .addComponent(jl_n3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_inLayout.createSequentialGroup()
                        .addComponent(jl_n2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_inLayout.createSequentialGroup()
                        .addComponent(jl_n1)
                        .addGap(27, 27, 27)
                        .addComponent(jtf_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jp_inLayout.setVerticalGroup(
            jp_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_inLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jp_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_n1)
                    .addComponent(jtf_n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jp_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_n2)
                    .addComponent(jtf_n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jp_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_n3)
                    .addComponent(jtf_n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lp_rb.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        Opciones.add(jrb_may);
        jrb_may.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jrb_may.setText("Mayor");

        Opciones.add(jrb_men);
        jrb_men.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jrb_men.setText("Menor");

        javax.swing.GroupLayout lp_rbLayout = new javax.swing.GroupLayout(lp_rb);
        lp_rb.setLayout(lp_rbLayout);
        lp_rbLayout.setHorizontalGroup(
            lp_rbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_rbLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(lp_rbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_men)
                    .addComponent(jrb_may))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        lp_rbLayout.setVerticalGroup(
            lp_rbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lp_rbLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jrb_may)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jrb_men)
                .addGap(10, 10, 10))
        );

        jp_bt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jb_com.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jb_com.setText("Comprobar");
        jb_com.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_comMouseClicked(evt);
            }
        });
        jb_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_comActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_btLayout = new javax.swing.GroupLayout(jp_bt);
        jp_bt.setLayout(jp_btLayout);
        jp_btLayout.setHorizontalGroup(
            jp_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_btLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jb_com, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jp_btLayout.setVerticalGroup(
            jp_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_btLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jb_com)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lp_rb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jp_bt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jp_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lp_rb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_comMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_comMouseClicked
        float n1;
        float n2;
        float n3;
        n1 = Float.parseFloat(this.jtf_n1.getText());
        n2 = Float.parseFloat(this.jtf_n2.getText());
        n3 = Float.parseFloat(this.jtf_n3.getText());
        if (jrb_may.isSelected()){
            if(n1>n2 && n1>n3){
                JOptionPane.showMessageDialog(this, "Mayor: "+n1);
            }
            else if(n2>n1 && n2>n3){
                JOptionPane.showMessageDialog(this, "Mayor: "+n2);
            }
            else if(n3>n1 && n3>n2){
                JOptionPane.showMessageDialog(this, "Mayor: "+n3);
            }
            else if(n2==n1 && n2==n3){
                JOptionPane.showMessageDialog(this, "Son iguales");
            }
        }
        if (jrb_men.isSelected()){
            if(n1<n2 && n1<n3){
                JOptionPane.showMessageDialog(this, "Menor: "+n1);
            }
            else if(n2<n1 && n2<n3){
                JOptionPane.showMessageDialog(this, "Menor: "+n2);
            }
            else if(n3<n1 && n3<n2){
                JOptionPane.showMessageDialog(this, "Menor: "+n3);
            }
            else if(n2==n1 && n2==n3){
                JOptionPane.showMessageDialog(this, "Son iguales");
            }
        }
    }//GEN-LAST:event_jb_comMouseClicked

    private void jb_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_comActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_comActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MayorMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MayorMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MayorMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MayorMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MayorMenor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Opciones;
    private javax.swing.JButton jb_com;
    private javax.swing.JLabel jl_n1;
    private javax.swing.JLabel jl_n2;
    private javax.swing.JLabel jl_n3;
    private javax.swing.JPanel jp_bt;
    private javax.swing.JPanel jp_in;
    private javax.swing.JRadioButton jrb_may;
    private javax.swing.JRadioButton jrb_men;
    private javax.swing.JTextField jtf_n1;
    private javax.swing.JTextField jtf_n2;
    private javax.swing.JTextField jtf_n3;
    private javax.swing.JPanel lp_rb;
    // End of variables declaration//GEN-END:variables
}
