/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author TeddyBear
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Calculadora = new javax.swing.JPanel();
        jl_peso = new javax.swing.JLabel();
        jl_altura = new javax.swing.JLabel();
        jtf_peso = new javax.swing.JTextField();
        jtf_altura = new javax.swing.JTextField();
        jb_calcular = new javax.swing.JButton();
        jb_clean = new javax.swing.JButton();
        jl_altura1 = new javax.swing.JLabel();
        jcb_sex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jframe_calculadora"); // NOI18N
        setResizable(false);

        jPanel_Calculadora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Calculadora de IMC", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N

        jl_peso.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_peso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_peso.setText("Peso (en Kg):");

        jl_altura.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_altura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_altura.setText("Altura (en cm):");

        jtf_peso.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_peso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_pesoKeyTyped(evt);
            }
        });

        jtf_altura.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_altura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_alturaKeyTyped(evt);
            }
        });

        jb_calcular.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jb_calcular.setText("Calcular");
        jb_calcular.setToolTipText("");
        jb_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_calcularMouseClicked(evt);
            }
        });

        jb_clean.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jb_clean.setText("Limpiar");
        jb_clean.setToolTipText("");
        jb_clean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cleanMouseClicked(evt);
            }
        });
        jb_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cleanActionPerformed(evt);
            }
        });

        jl_altura1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jl_altura1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_altura1.setText("Sexo:");

        jcb_sex.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcb_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona uno", "Femenino", "Masculino" }));

        javax.swing.GroupLayout jPanel_CalculadoraLayout = new javax.swing.GroupLayout(jPanel_Calculadora);
        jPanel_Calculadora.setLayout(jPanel_CalculadoraLayout);
        jPanel_CalculadoraLayout.setHorizontalGroup(
            jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CalculadoraLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_altura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_peso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_altura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_altura)
                    .addComponent(jtf_peso)
                    .addComponent(jb_clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel_CalculadoraLayout.setVerticalGroup(
            jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CalculadoraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_peso)
                    .addComponent(jtf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_altura)
                    .addComponent(jtf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_altura1)
                    .addComponent(jcb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_calcular)
                    .addComponent(jb_clean))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel_Calculadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel_Calculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_calcularMouseClicked
        try {
            double peso;
            double altura;
            double imc;
            peso = Double.parseDouble(this.jtf_peso.getText());
            altura = Double.parseDouble(this.jtf_altura.getText());
            if(peso==0 || altura==0){
                JOptionPane.showMessageDialog(this,"No puedes poner el cero ahi");
            }
            else if(peso<0 || altura<0){
                JOptionPane.showMessageDialog(this,"Upps! No puedes usar numeros negativos");
            }
            else if(altura>250){
                JOptionPane.showMessageDialog(this,"A menos que seas pie grande,\nte recomendamos usar tu altura real");
            }
            else if(altura<50){
                JOptionPane.showMessageDialog(this,"A menos que seas Chandra Bahadur Dangi,\nte recomendamos usar tu altura real");
            }
            else if(peso<25){
                JOptionPane.showMessageDialog(this,"A menos que seas Valeria Levitin,\nte recomendamos usar tu peso real");
            }
            else{
                altura=altura/100;
                imc=peso/(altura*altura);
                DecimalFormat formato = new DecimalFormat("#.00");

                switch (jcb_sex.getSelectedIndex()){
                    case 0:
                        JOptionPane.showMessageDialog(this,"Upps! Olvidaste especificar tu sexo");
                        break;
                    case 1:
                        if(imc<19){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes desnutricion");
                        }
                        else if(imc>=19 && imc<24){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tu peso es normal");
                        }
                        else if(imc>=24 && imc<27){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes sobrepeso");
                        }
                        else if(imc>=27 && imc<32){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes obesidad");
                        }
                        else if(imc>=32){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes obesidad grave");
                        }
                        break;
                        case 2: // hombre
                        if(imc<20){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes desnutricion");
                        }
                        else if(imc>=20 && imc<24){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tu peso es normal");
                        }
                        else if(imc>=24 && imc<30){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes sobrepeso");
                        }
                        else if(imc>=30 && imc<40){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes obesidad");
                        }
                        else if(imc>=40){
                            JOptionPane.showMessageDialog(this,"Tu IMC es de: "+formato.format(imc)+"\n Esto significa que tienes obesidad grave");
                        }
                        break;
                }
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Upps! No puedo dejar que escribas eso ahi");
        }
    }//GEN-LAST:event_jb_calcularMouseClicked

    private void jb_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cleanActionPerformed

    private void jtf_pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_pesoKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) { 
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Upps! No puedo dejar que escribas eso ahi");   
        }    
    }//GEN-LAST:event_jtf_pesoKeyTyped

    private void jtf_alturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_alturaKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)) { 
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Upps! No puedo dejar que escribas eso ahi");   
        }
    }//GEN-LAST:event_jtf_alturaKeyTyped

    private void jb_cleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cleanMouseClicked
        this.jtf_altura.setText(null);
        this.jtf_peso.setText(null);
        this.jcb_sex.setSelectedIndex(0);
    }//GEN-LAST:event_jb_cleanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_Calculadora;
    private javax.swing.JButton jb_calcular;
    private javax.swing.JButton jb_clean;
    private javax.swing.JComboBox<String> jcb_sex;
    private javax.swing.JLabel jl_altura;
    private javax.swing.JLabel jl_altura1;
    private javax.swing.JLabel jl_peso;
    private javax.swing.JTextField jtf_altura;
    private javax.swing.JTextField jtf_peso;
    // End of variables declaration//GEN-END:variables
}
